### ISSUE TITLE
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.

### ISSUE THREAD

**Issue by amirasrasami** [junzis/openap-top#13]
When I am trying to install necessary packages with `conda install cfgrib cartopy casadi scikit-learn -c conda-forge
`
Here is what I get.
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \

The last "Solving environment: \" runs indefinitely.

**Comment by junzis** [comment]
i recommend to use `mamba` instead of `conda`
